### ISSUE TITLE
Editor编译执行画面黑块闪烁

### ISSUE THREAD

**Issue by The-five-stooges** [BoomingTech/Pilot#138] opened 2022-04-23 06:58 UTC
效果如图所示：
<img width="651" alt="8741bb3bb057001c482fa24d373b2c0" src="https://user-images.githubusercontent.com/18204304/164883890-11a45c5b-0d0d-487b-aed4-02ecc25c3921.png">
<img width="651" alt="481e437119c08838e3a456d827fc0af" src="https://user-images.githubusercontent.com/18204304/164883893-4e3aae5f-c25e-40d0-8f82-0ee6af05355e.png">

**Desktop | 桌面环境**
 - OS: Windows
 - Version Win11
 - CPU Ryzen 3600
 - GPU AMD 6700 XT
 - Memory 32GB
 - Compiler VS2022

**Comment by hyv1001** [comment] 2022-04-26 10:59
It may be caused by float precision, we just fixed a related issue by #153 
You could try to check this problem again with the latest code

**Comment by v4vendeta** [comment] 2022-04-26 11:22
@hyv1001 this issue should also be addressed in other branches.

**Comment by hyv1001** [comment] 2022-05-01 14:37
> @hyv1001 branch homework01/homework02 have this issue too.

The main branch has merged into the homework02 branch, plz reopen it or create a new ticket if this issue still exists.

**Closed by hyv1001** 2022-05-01 14:37 UTC
Labels: bug
